version: '3.4'
services:
  java:
    image: adoptopenjdk/openjdk11:centos
    env_file: .env
    ports: 
      - "8080:8080"
    volumes:
      - .:/opt/app
      - $HOME/.gradle:/root/.gradle
    working_dir: /opt/app

  musketeers:
    image: flemay/musketeers
    volumes:
      - .:/opt/app
    working_dir: /opt/app